services:
  backend-php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog-backend-php
    restart: unless-stopped
    environment:
      APP_ENV: dev
    volumes:
      - ./backend:/var/www/html:cached
    depends_on:
      - db

  backend-nginx:
    image: nginx:1.25-alpine
    container_name: blog-backend-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend-php

  db:
    image: postgres:16
    container_name: blog-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symphony
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "54320:5432"

volumes:
  db-data:
